# Base configs
baseurl: "https://braydonp.github.io/photography/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Braydon Prack"
subtitle: "a collection of my favourites"
author: "Braydon Prack"
header:
 title: "Photography"
 subtitle: "by Braydon Prack"
footer:
 name: "Hey there, my name is Braydon"
 bio: "I am a photographer just carrying my camera around and capturing."
 github: "Feel free to contac me on LinkedIn if you want to connect! <a href=\"https://www.linkedin.com/in/braydonprack/"></a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/braydonprack/"
  github: "https://www.github.com/rampatra"
